services:
  - type: web
    name: brainapi
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt && python run_migration.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.14"
      - key: PORT
        value: "10000"
